### ISSUE TITLE
NameError: global name 'epoll' is not defined

### ISSUE THREAD

**Issue by Elaoed** [maliubiao/simple_http#2]
import async_http
In [3]: def print_it(x):
   ...:     print "hello"
async_http.repeat_tasks([{"url": "http://www.baidu.com", "parser": print_it}])
希望作者能够给个解决方案~

**Comment by Elaoed** [comment]
NameError: global name 'epoll' is not defined

**Comment by maliubiao** [comment]
这个Linux下才能用的 。。。， windows没有EPOLL

**Comment by Elaoed** [comment]
对 我用的macos 底层用的是kqueue 之前不知道 一直以为macos底层也是epoll. 希望作者能够添加对此块的支持
